# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amplivum
description: Amplectere Privatum
baseurl: ""
url: http://www.amplivum.com
repository: 348ab1a8-424a-43d8-b463-8e925d751c7f/amplivum.github.io

# Logo
#logo: "/assets/images/"
#favicon_ico: "/assets/images/favicon.ico"

# Theme
theme: just-the-docs

just_the_docs:
  color_scheme: dark